### ISSUE TITLE
Loading Error with Spigot 1.8.7

### ISSUE THREAD

**Issue by mrm1st3r** [DarkBlade12/EnchantPlus#1]
When using this plugin with spigot for minecraft 1.8.7 it crashes during startup with the following exception:

```
Could not load 'plugins/EnchantPlus_1.3.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/darkblade12/enchantplus/EnchantPlus : Unsupported major.minor version 52.0
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-f94fe8f-d27e6d0]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-f94fe8f-d27e6d0]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.lang.UnsupportedClassVersionError: com/darkblade12/enchantplus/EnchantPlus : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_65]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_65]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_65]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_65]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_65]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_65]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_65]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_65]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_65]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-f94fe8f-d27e6d0]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-f94fe8f-d27e6d0]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_65]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_65]
    at java.lang.Class.forName(Class.java:270) ~[?:1.7.0_65]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-f94fe8f-d27e6d0]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-f94fe8f-d27e6d0]
    ... 6 more
```

**Comment by DarkBlade12** [comment]
It should work fine, if you update your server to the latest Java version!

**Comment by mrm1st3r** [comment]
The Server is currently running Debian Wheezy with OpenJDK7 (latest version at the time of writing). I might try upgrading to Jessie / OpenJDK8

**Comment by mrm1st3r** [comment]
OK, upgrading to Java 8 did the job. It might be nice for others to put a notice on the project page as I'm sure I'm not the only one with this problem.

**Comment by DarkBlade12** [comment]
Well there's a note on the file of the download page now which states that Java 8 is required. However I may upload a version for Java 7 since many people are still running that.
